name: Build Windows

on:
  workflow_call:
    inputs:
      version:
        description: "tag name"
        required: false
        type: string

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            %LOCALAPPDATA%\Pub\Cache
          key: windows-pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            windows-pub-${{ runner.os }}-

      - name: Setup build environment
        id: setup
        uses: ./.github/actions/setup
        with:
          version: ${{ inputs.version }}

      - name: Build Windows
        run: |
          flutter build windows --release \
            --dart-define=GIT_TAG=${{ steps.setup.outputs.GIT_TAG }} \
            --dart-define=GIT_COMMIT=${{ steps.setup.outputs.GIT_COMMIT }} \
            --dart-define=GIT_COMMIT_DATE=${{ steps.setup.outputs.GIT_COMMIT_DATE }} \
            --dart-define=SENTRY_DSN="${{ secrets.SENTRY_DSN }}"
        shell: bash

      - name: Archive Windows Release
        run: Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath
          windows-release.zip

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: windows-release.zip
